version: "3.7" #Docker-compose 버전, 2버전과 3버전은 차이가 큼
services:
  my-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/project3/
      - /project3/node_modules #node_modules 볼륨 제외
    ports:
      - 8000:3000
  my-database:
    platform: linux/x86_64 #M1사용시
    image: mariadb:latest
    #   build:
    #     context: ./database
    #     dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: "mydocker03"
      MYSQL_ROOT_PASSWORD: "1111"
    ports:
      - 3306:3306
    volumes:
      - ./local-mariadb:/var/lib/mysql
  my-redis:
    image: redis:latest
    ports:
      - 6379:6379
  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
  logstash:
    image: logstash:7.17.0
    volumes:
      - ./backend/elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #logstash 설정파일 옮겨주기
      - ./backend/elk/logstash/mysql-connector-java-8.0.28.jar:/usr/share/logstash/mysql-connector-java-8.0.28.jar #드라이버
  kibana:
    image: kibana:7.17.0
    environment:
      ELASTICSEARCH_UTL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
