version: "3.7"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    volumes:
      - ./api-gateway/src:/api-gateway/src
      - /api-gateway/node_modules
    ports:
      - 3000:3000 #게이트웨이 포트포워딩
  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth/src:/auth-service/src
      - /services/auth/node_modules
  resource-service:
    build:
      context: ./services/resource
      dockerfile: Dockerfile
    volumes:
      - ./services/resource/src:/resource-service/src
      - /services/resource/node_modules
